markdown: kramdown
permalink: /:categories/:year/:title/
paginate: 5
paginate_path: /blog/page:num/
exclude:
  - package.json
  - Gruntfile.js
  - node_modules

defaults:
  -
    scope:
      type: posts
    values:
      layout: blog
      categories: blog

github_avatars:
  lamallam: "https://s3.eu-west-2.amazonaws.com/afroware/images/me.jpg"

gems: [jekyll-paginate]
